{{- define "library-chart.configMap" -}}
{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}-cm
data:
  {{- with .Values.configMap.data }}
  {{- toYaml  . | nindent 2 }}
  {{- end -}}
{{- end -}}
{{- end -}}