{{- define "library-chart.jobRbac" -}}
{{- if and .Values.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "library-chart.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch", "extensions"]
  resources: ["cronjobs"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "get"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments","deployments/scale"]
  verbs: ["*"]
{{- if .Values.rbac.extraRules }}
{{- with .Values.rbac.extraRules  }}
{{ tpl (toYaml .) $ }}

{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "library-chart.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "library-chart.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "library-chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}