{{- define "library-chart.secret" -}}
{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "library-chart.fullname" . }}-secret
data:
  {{- with .Values.secret.data }}
  {{- range $key, $value := . }}
   {{ $key }}: {{ tpl $value $ | b64enc | quote | nindent 4 }}
    
  {{- end }}
 {{- end }}
{{- end -}}
{{- end -}}