{{- define "library-chart.serviceAccount" -}}
{{- if and .Values.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "library-chart.serviceAccountName" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations -}}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml .) $ | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}