# Default values for test2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


global:
  image:
    registry: docker.io
    repository: nginx
    # tag: ""
  env:
    data:
      name: global-env
      value: global-val 

enabled: true
# daemonset: 
#   enabled: true
image:  
  repository: nginx
replicaCount: 2
extraLabels:
  app: app1
expose:
  port: 79
  protocol: UDP
postStart: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
preStop:
- "echo"
- "how are you"
- ">"
- "./pppp"
# initContainers:
# - image: busybox
#   name: init
#   env:
#   - name: "init-env1"
#     value: "val1"
# extraContainers:
# - image:  image
#   name:  my-name
#   env:
#   - name: "extra"
#     value: "extra-val1"

# service:
  # portName: api
  # port: 555
  # protocol: UDP
  # extraPorts:
  # - name: ngnix-test3
    # port: 888
  
# ingress:
#   port: 778
#   path: /api/

# job:
#   image:
#     repository: busybox
#     tag: "22"
#   extraContainers:
#   - image: abc
#     name: second-container
#     command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]

# configMap:
#   mount: /mount/path
#   data:
#     file1: |
#       this is the data
#       line2
#       line3
#     file3: |
#       line4
#       line5

# secret:
#   mount: /mount/path
#   data:
#     ca.crt: |
#       dadsadsa
#       sdadasdas
#       dasdadsads
#       dasdddd
#     tls.crt: |
#       abcde
#       fghij
#       klmno
#       pqrst
#       uvwxy
    