# Default values for test2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: false
replicaCount: 1

# image:
#   registry: docker.io
#   repository: ubuntu
#   # Overrides the image tag whose default is the chart appVersion.
#   tag: ""


    